# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/images"
publish_mode: editorial_workflow
site_url: "http://erc.cuhk.edu.hk/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{fields.categories}}/{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "tags", name: "tags", widget: "list", required: false }
      - {
          label: "categories",
          name: "categories",
          widget: "list",
          required: false,
        }
      - { label: "execept", name: "execept", widget: "string", required: false }
      - { label: "tagline", name: "tagline", widget: "string", required: false }
      - label: "sidebar"
        name: "sidebar"
        widget: "list"
        required: false
        fields:
          - {
              label: "image",
              name: "image",
              widget: "image",
              allow_mulitple: false,
              required: false,
            }
