# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: blog/{{slug}}
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "tags", name: "tags", widget: "list", default: ["others"] }
      - {
          label: "categories",
          name: "categories",
          widget: "list",
          default: ["APEC Study Centre"],
        }
      - { label: "execept", name: "execept", widget: "string" }
      - { label: "tagline", name: "tagline", widget: "string" }
      - label: "sidebar"
        name: "sidebar"
        widget: "list"
        fields:
          - {
              label: "image",
              name: "image",
              widget: "image",
              allow_mulitple: false,
              default: "",
            }
